# frozen_string_literal: true

source "https://rubygems.org"

gem 'rspec'
gem 'mqtt', '~> 0.5'
gem 'dotenv', '~> 2.6'
gem 'multipart-post'
gem 'net-ping'
gem 'milight-easybulb', '~> 1.0'
gem 'chroma', '~> 0.2.x'