/* tslint:disable */
/* eslint-disable */
/**
 * ESP8266 MiLight Hub
 * Official documention for MiLight Hub\'s REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: chris@sidoh.org
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

