name: Publish Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git fetch --tags --force origin
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Prepare release
        run: |
          ./.prepare_release

      - name: Create Release
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            console.log('environment', process.versions);
            
            const fs = require('fs').promises;
            
            const { repo: { owner, repo }, sha } = context;
            console.log({ owner, repo, sha });

            const release = await github.repos.createRelease({
              owner, repo,
              name: process.env.GITHUB_REF_NAME,
              body: await fs.readFile('./dist/release-notes.txt', 'utf8'),
              tag_name: process.env.GITHUB_REF,
              draft: true,
              target_commitish: sha
            });

            console.log('created release', { release });
        
            for (let file of await fs.readdir('dist')) {
              if (file.endsWith('.bin')) {
                console.log('uploading', file);

                await github.repos.uploadReleaseAsset({
                  owner, repo,
                  release_id: release.data.id,
                  name: file,
                  data: await fs.readFile(`./dist/${file}`)
                });            
              }
            }

  publish_docs:
    needs: build
    runs-on: ubuntu-latest

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Build docs
        run: |
          npm install -g swagger-cli redoc-cli
          swagger-cli validate ./docs/openapi.yaml
          ./.prepare_docs

      - name: Release docs
        id: deployment
        uses: actions/deploy-pages@v2
      - name: Release docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/docs # The folder the action should deploy.